#include "crypto/openssl/SpcStructures.h"

ASN1_SEQUENCE(SPC_SP_AGENCY_INFO) = {
    ASN1_IMP_OPT(SPC_SP_AGENCY_INFO, policyInformation, ASN1_IA5STRING, 0),
} ASN1_SEQUENCE_END(SPC_SP_AGENCY_INFO);

IMPLEMENT_ASN1_FUNCTIONS(SPC_SP_AGENCY_INFO);
